from flask import Flask, request, jsonify
import os
import openai

app = Flask(__name__)

# Load OpenAI API key from environment variable
openai.api_key = os.environ.get("OPENAI_API_KEY")

@app.route('/summarize', methods=['POST'])
def summarize_text():
    """
    Receives text content and returns a summary generated by OpenAI.
    """
    if not openai.api_key:
        return jsonify({"error": "OpenAI API key not configured."}), 500

    data = request.get_json()
    if not data or 'text' not in data:
        return jsonify({"error": "Invalid request body. 'text' field is required."}), 400

    text_to_summarize = data['text']

    try:
        response = openai.Completion.create(
            model="gpt-3.5-turbo-instruct",  # Or another suitable model
            prompt=f"Please summarize the following text:\n\n{text_to_summarize}",
            max_tokens=150
        )
        summary = response.choices[0].text.strip()
        return jsonify({"summary": summary}), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)
